const labels = {
    en: {
        title: "Germany’s Overshoot Dashboard",
        description: "Discover what drives Overshoot Day",
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",

        overshootDay: "Overshoot Day – [Country]",

        biocapacityVsEcologicalFootprint: "Capacity vs. Demand",

        earthsNeeded: "Earths Needed if everyone lived like {country}: {number}",
        biocapacityBreakdown: "Biocapacity Breakdown",
        footprintBreakdown: "Footprint Breakdown",
        worldBaseline: "World Baseline",
        exploreByCountry: "Explore Overshoot by Country",
        simulationTimeline: "How Demand Exceeds Supply",
        world: "World",
        france: "France",
        germany: "Germany",
        poland: "Poland",
        afghanistan: "Afghanistan",
        albania: "Albania",
        algeria: "Algeria",
        argentina: "Argentina",
        austria: "Austria",
        barbados: "Barbados",
        bolivia: "Bolivia",
        brazil: "Brazil",
        myanmar: "Myanmar",
        burundi: "Burundi",
        cameroon: "Cameroon",
        canada: "Canada",
        sriLanka: "Sri Lanka",
        chad: "Chad",
        chile: "Chile",
        colombia: "Colombia",
        congo: "Congo",
        costaRica: "Costa Rica",
        benin: "Benin",
        denmark: "Denmark",
        dominicanRepublic: "Dominican Republic",
        egypt: "Egypt",
        elSalvador: "El Salvador",
        fiji: "Fiji",
        gambia: "Gambia",
        ghana: "Ghana",
        greece: "Greece",
        guatemala: "Guatemala",
        guinea: "Guinea",
        haiti: "Haiti",
        hungary: "Hungary",
        india: "India",
        indonesia: "Indonesia",
        israel: "Israel",
        italy: "Italy",
        coteDIvoire: "C\u00f4te d'Ivoire",
        japan: "Japan",
        kenya: "Kenya",
        koreaDemocraticPeoplesRepublicOf: "Korea, Democratic People's Republic of",
        koreaRepublicOf: "Korea, Republic of",
        liberia: "Liberia",
        madagascar: "Madagascar",
        mali: "Mali",
        mexico: "Mexico",
        mongolia: "Mongolia",
        mozambique: "Mozambique",
        nepal: "Nepal",
        netherlands: "Netherlands",
        nicaragua: "Nicaragua",
        niger: "Niger",
        nigeria: "Nigeria",
        norway: "Norway",
        pakistan: "Pakistan",
        peru: "Peru",
        philippines: "Philippines",
        portugal: "Portugal",
        romania: "Romania",
        rwanda: "Rwanda",
        somalia: "Somalia",
        southAfrica: "South Africa",
        spain: "Spain",
        sweden: "Sweden",
        switzerland: "Switzerland",
        thailand: "Thailand",
        togo: "Togo",
        turkiye: "Türkiye",
        uganda: "Uganda",
        unitedKingdom: "United Kingdom",
        unitedStatesOfAmerica: "United States of America",
        burkinaFaso: "Burkina Faso",
        venezuelaBolivarianRepublicOf: "Venezuela, Bolivarian Republic of",
        vietNam: "Viet Nam",
        congoDemocraticRepublicOf: "Congo, Democratic Republic of",
        belgium: "Belgium",
        luxembourg: "Luxembourg",
        china: "China",
        malawi: "Malawi",
        tanzaniaUnitedRepublicOf: "Tanzania, United Republic of",
        panama: "Panama",
        guineaBissau: "Guinea-Bissau",
        bahamas: "Bahamas",
        bangladesh: "Bangladesh",
        bhutan: "Bhutan",
        bahrain: "Bahrain",
        qatar: "Qatar",
        oman: "Oman",
        armenia: "Armenia",
        belarus: "Belarus",
        estonia: "Estonia",
        bosniaAndHerzegovina: "Bosnia and Herzegovina",
        croatia: "Croatia",
        latvia: "Latvia",
        lithuania: "Lithuania",
        russianFederation: "Russian Federation",
        republicOfNorthMacedonia: "Republic of North Macedonia",
        czechRepublic: "Czech Republic",
        eritrea: "Eritrea",
        slovakia: "Slovakia",
        ethiopia: "Ethiopia",
        kyrgyzstan: "Kyrgyzstan",
        kuwait: "Kuwait",
        zambia: "Zambia",
        serbia: "Serbia",
        montenegro: "Montenegro",
        sudan: "Sudan",
        angola: "Angola",
        australia: "Australia",
        bulgaria: "Bulgaria",
        caboVerde: "Cabo Verde",
        centralAfricanRepublic: "Central African Republic",
        cuba: "Cuba",
        cyprus: "Cyprus",
        ecuador: "Ecuador",
        finland: "Finland",
        gabon: "Gabon",
        grenada: "Grenada",
        honduras: "Honduras",
        iranIslamicRepublicOf: "Iran, Islamic Republic of",
        iraq: "Iraq",
        ireland: "Ireland",
        cambodia: "Cambodia",
        lebanon: "Lebanon",
        malaysia: "Malaysia",
        malta: "Malta",
        mauritania: "Mauritania",
        mauritius: "Mauritius",
        morocco: "Morocco",
        namibia: "Namibia",
        newZealand: "New Zealand",
        papuaNewGuinea: "Papua New Guinea",
        paraguay: "Paraguay",
        timorLeste: "Timor-Leste",
        zimbabwe: "Zimbabwe",
        saintLucia: "Saint Lucia",
        saoTomeAndPrincipe: "Sao Tome and Principe",
        senegal: "Senegal",
        sierraLeone: "Sierra Leone",
        tonga: "Tonga",
        tunisia: "Tunisia",
        samoa: "Samoa",
        yemen: "Yemen",
        frenchPolynesia: "French Polynesia",
        botswana: "Botswana",
        lesotho: "Lesotho",
        trinidadAndTobago: "Trinidad and Tobago",
        singapore: "Singapore",
        antiguaAndBarbuda: "Antigua and Barbuda",
        eswatini: "Eswatini",
        georgia: "Georgia",
        slovenia: "Slovenia",
        tajikistan: "Tajikistan",
        turkmenistan: "Turkmenistan",
        ukraine: "Ukraine",
        uzbekistan: "Uzbekistan",
        azerbaijan: "Azerbaijan",
        stateOfPalestine: "State of Palestine",
        southSudan: "South Sudan",
        solomonIslands: "Solomon Islands",
        equatorialGuinea: "Equatorial Guinea",
        guyana: "Guyana",
        kazakhstan: "Kazakhstan",
        jordan: "Jordan",
        saudiArabia: "Saudi Arabia",
        suriname: "Suriname",
        dominica: "Dominica",
        djibouti: "Djibouti",
        laoPeoplesDemocraticRepublic: "Lao People's Democratic Republic",
        saintVincentAndGrenadines: "Saint Vincent and Grenadines",
        unitedArabEmirates: "United Arab Emirates",
        cropLand: "Crop Land",
        grazingLand: "Grazing Land",
        forestLand: "Forest Land",
        fishingGround: "Fishing Ground",
        builtUpLand: "Built-up Land",
        carbon: "Carbon",


        biocapacityCarbonTitle: "Biocapacity & Carbon: World vs. [Country]",
        biocapacityCarbonTooltip: "Shows the trend of biocapacity and carbon footprint over time. Data source: Global Footprint Network (GFN), National Footprint Accounts",


        germanyCo2EnergyTitle: "Germany: CO₂ & Energy by Sector",
        germanyCo2BySector: "CO₂ Emissions by Sector",
        germanyEnergyBySector: "Energy Use by Sector",
        germanyCo2EnergyTooltip: "Shows the sectoral share of CO₂ emissions and energy use in Germany. Data source: Global Footprint Network (GFN) and national statistics.",


        co2EnergyTrendsTitle: "Germany: CO₂ & Energy Trends (1990–2024)",
        co2EnergyTrendsSubheading: "Sector Insights – Germany",
        co2EnergyTrendsCo2ChartTitle: "CO₂ Emissions by Sector (1990–2024)",
        co2EnergyTrendsEnergyChartTitle: "Energy Use by Sector (1990–2024)",
        co2EnergyTrendsTooltip: "Shows sector-wise CO₂ emissions and energy consumption in Germany from 1990 to 2024. Data source: Global Footprint Network (GFN) and national energy statistics.",




        submit: "Submit",
        cancel: "Cancel",

        overshootLater: "+{days} days later than world",
        overshootEarlier: "-{days} days earlier than world",

        simulatorTitle: "Overshoot Day Scenario Simulator",
        simulatorSubheading: "Data available for 1990–2024",
        simulatorIntro: "Adjust sectoral use to see how Overshoot Day shifts.",
        simulatorSelectDates: "Select Dates",
        simulatorBaseline: "Baseline",
        simulatorAdjusted: "Adjusted",
        simulatorDifference: "Difference",
        simulatorInfoTitle: "About this Simulator",
        simulatorInfoBody: "Adjust the sliders to explore how sectoral CO₂ emissions influence Overshoot Day. Data source: Global Footprint Network (GFN), sectoral CO₂ breakdown (1990–2024)."
    },
    de: {
        title: "Deutschlands Erdüberlastungs-Dashboard",
        description: "Entdecke, was den Erdüberlastungstag antreibt",
        january: "Januar",
        february: "Februar",
        march: "März",
        april: "April",
        may: "Mai",
        june: "Juni",
        july: "Juli",
        august: "August",
        september: "September",
        october: "Oktober",
        november: "November",
        december: "Dezember",

        overshootDay: "Erdüberlastungstag – [Land]",

        biocapacityVsEcologicalFootprint: "Kapazität vs. Nachfrage",
        world: "Welt",
        france: "Frankreich",
        germany: "Deutschland",
        poland: "Polen",
        afghanistan: "Afghanistan",
        albania: "Albanien",
        algeria: "Algerien",
        argentina: "Argentinien",
        austria: "Österreich",
        barbados: "Barbados",
        bolivia: "Bolivien",
        brazil: "Brasilien",
        myanmar: "Myanmar",
        burundi: "Burundi",
        cameroon: "Kamerun",
        canada: "Kanada",
        sriLanka: "Sri Lanka",
        chad: "Tschad",
        chile: "Chile",
        colombia: "Kolumbien",
        congo: "Kongo",
        costaRica: "Costa Rica",
        benin: "Benin",
        denmark: "Dänemark",
        dominicanRepublic: "Dominikanische Republik",
        egypt: "Ägypten",
        elSalvador: "El Salvador",
        fiji: "Fidschi",
        gambia: "Gambia",
        ghana: "Ghana",
        greece: "Griechenland",
        guatemala: "Guatemala",
        guinea: "Guinea",
        haiti: "Haiti",
        hungary: "Ungarn",
        india: "Indien",
        indonesia: "Indonesien",
        israel: "Israel",
        italy: "Italien",
        coteDIvoire: "Elfenbeinküste",
        japan: "Japan",
        kenya: "Kenia",
        koreaDemocraticPeoplesRepublicOf: "Demokratische Volksrepublik Korea",
        koreaRepublicOf: "Republik Korea",
        liberia: "Liberia",
        madagascar: "Madagaskar",
        mali: "Mali",
        mexico: "Mexiko",
        mongolia: "Mongolei",
        mozambique: "Mosambik",
        nepal: "Nepal",
        netherlands: "Niederlande",
        nicaragua: "Nicaragua",
        niger: "Niger",
        nigeria: "Nigeria",
        norway: "Norwegen",
        pakistan: "Pakistan",
        peru: "Peru",
        philippines: "Philippinen",
        portugal: "Portugal",
        romania: "Rumänien",
        rwanda: "Ruanda",
        somalia: "Somalia",
        southAfrica: "Südafrika",
        spain: "Spanien",
        sweden: "Schweden",
        switzerland: "Schweiz",
        thailand: "Thailand",
        togo: "Togo",
        turkiye: "Türkei",
        uganda: "Uganda",
        unitedKingdom: "Vereinigtes Königreich",
        unitedStatesOfAmerica: "Vereinigte Staaten von Amerika",
        burkinaFaso: "Burkina Faso",
        venezuelaBolivarianRepublicOf: "Bolivarische Republik Venezuela",
        vietNam: "Vietnam",
        congoDemocraticRepublicOf: "Demokratische Republik Kongo",
        belgium: "Belgien",
        luxembourg: "Luxemburg",
        china: "China",
        malawi: "Malawi",
        tanzaniaUnitedRepublicOf: "Vereinigte Republik Tansania",
        panama: "Panama",
        guineaBissau: "Guinea-Bissau",
        bahamas: "Bahamas",
        bangladesh: "Bangladesch",
        bhutan: "Bhutan",
        bahrain: "Bahrain",
        qatar: "Katar",
        oman: "Oman",
        armenia: "Armenien",
        belarus: "Belarus",
        estonia: "Estland",
        bosniaAndHerzegovina: "Bosnien und Herzegowina",
        croatia: "Kroatien",
        latvia: "Lettland",
        lithuania: "Litauen",
        russianFederation: "Russische Föderation",
        republicOfNorthMacedonia: "Republik Nordmazedonien",
        czechRepublic: "Tschechische Republik",
        eritrea: "Eritrea",
        slovakia: "Slowakei",
        ethiopia: "Äthiopien",
        kyrgyzstan: "Kirgisistan",
        kuwait: "Kuwait",
        zambia: "Sambia",
        serbia: "Serbien",
        montenegro: "Montenegro",
        sudan: "Sudan",
        angola: "Angola",
        australia: "Australien",
        bulgaria: "Bulgarien",
        caboVerde: "Kap Verde",
        centralAfricanRepublic: "Zentralafrikanische Republik",
        cuba: "Kuba",
        cyprus: "Zypern",
        ecuador: "Ecuador",
        finland: "Finnland",
        gabon: "Gabun",
        grenada: "Grenada",
        honduras: "Honduras",
        iranIslamicRepublicOf: "Islamische Republik Iran",
        iraq: "Irak",
        ireland: "Irland",
        cambodia: "Kambodscha",
        lebanon: "Libanon",
        malaysia: "Malaysia",
        malta: "Malta",
        mauritania: "Mauretanien",
        mauritius: "Mauritius",
        morocco: "Marokko",
        namibia: "Namibia",
        newZealand: "Neuseeland",
        papuaNewGuinea: "Papua-Neuguinea",
        paraguay: "Paraguay",
        timorLeste: "Timor-Leste",
        zimbabwe: "Simbabwe",
        saintLucia: "St. Lucia",
        saoTomeAndPrincipe: "São Tomé und Príncipe",
        senegal: "Senegal",
        sierraLeone: "Sierra Leone",
        tonga: "Tonga",
        tunisia: "Tunesien",
        samoa: "Samoa",
        yemen: "Jemen",
        frenchPolynesia: "Französisch-Polynesien",
        botswana: "Botswana",
        lesotho: "Lesotho",
        trinidadAndTobago: "Trinidad und Tobago",
        singapore: "Singapur",
        antiguaAndBarbuda: "Antigua und Barbuda",
        eswatini: "Eswatini",
        georgia: "Georgien",
        slovenia: "Slowenien",
        tajikistan: "Tadschikistan",
        turkmenistan: "Turkmenistan",
        ukraine: "Ukraine",
        uzbekistan: "Usbekistan",
        azerbaijan: "Aserbaidschan",
        stateOfPalestine: "Staat Palästina",
        southSudan: "Südsudan",
        solomonIslands: "Salomonen",
        equatorialGuinea: "Äquatorialguinea",
        guyana: "Guyana",
        kazakhstan: "Kasachstan",
        jordan: "Jordanien",
        saudiArabia: "Saudi-Arabien",
        suriname: "Suriname",
        dominica: "Dominica",
        djibouti: "Dschibuti",
        laoPeoplesDemocraticRepublic: "Demokratische Volksrepublik Laos",
        saintVincentAndGrenadines: "St. Vincent und die Grenadinen",
        unitedArabEmirates: "Vereinigte Arabische Emirate",
        cropLand: "Ackerland",
        grazingLand: "Weideland",
        forestLand: "Waldfläche",
        fishingGround: "Fischgründe",
        builtUpLand: "Bebaute Fläche",
        carbon: "Kohlenstoff",


        biocapacityCarbonTitle: "Biokapazität & Kohlenstoff: Welt vs. [Land]",
        biocapacityCarbonTooltip: "Zeigt den Verlauf der Biokapazität und des CO₂-Fußabdrucks im Zeitverlauf. Datenquelle: Global Footprint Network (GFN), Nationale Footprint-Konten",


        germanyCo2EnergyTitle: "Deutschland: CO₂ & Energie nach Sektor",
        germanyCo2BySector: "CO₂-Emissionen nach Sektor",
        germanyEnergyBySector: "Energieverbrauch nach Sektor",
        germanyCo2EnergyTooltip: "Zeigt den Anteil der CO₂-Emissionen und des Energieverbrauchs in Deutschland nach Sektor. Datenquelle: Global Footprint Network (GFN) und nationale Statistiken.",


        co2EnergyTrendsTitle: "Deutschland: CO₂- und Energietrends (1990–2024)",
        co2EnergyTrendsSubheading: "Sektor-Insights – Deutschland",
        co2EnergyTrendsCo2ChartTitle: "CO₂-Emissionen nach Sektor (1990–2024)",
        co2EnergyTrendsEnergyChartTitle: "Energieverbrauch nach Sektor (1990–2024)",
        co2EnergyTrendsTooltip: "Zeigt die sektorweisen CO₂-Emissionen und den Energieverbrauch in Deutschland von 1990 bis 2024. Datenquelle: Global Footprint Network (GFN) und nationale Energiestatistiken.",


        earthsNeeded: "Benötigte Erden, wenn alle lebten wie {country}: {number}",
        biocapacityBreakdown: "Biokapazitätsaufteilung",
        footprintBreakdown: "Fußabdruck-Aufteilung",
        worldBaseline: "Welt-Basislinie",
        exploreByCountry: "Erdüberlastung nach Land erkunden",
        simulationTimeline: "Wie die Nachfrage das Angebot übersteigt",




        submit: "Absenden",
        cancel: "Abbrechen",

        overshootLater: "+{days} Tage später als die Welt",
        overshootEarlier: "-{days} Tage früher als die Welt",

        simulatorTitle: "Szenariosimulator für den Erdüberlastungstag",
        simulatorSubheading: "Daten verfügbar für 1990–2024",
        simulatorIntro: "Passe die sektorale Nutzung an, um zu sehen, wie sich der Erdüberlastungstag verschiebt.",
        simulatorSelectDates: "Daten auswählen",
        simulatorBaseline: "Basiswert",
        simulatorAdjusted: "Angepasst",
        simulatorDifference: "Differenz",
        simulatorInfoTitle: "Über diesen Simulator",
        simulatorInfoBody: "Passe die Schieberegler an, um zu erkunden, wie sektorale CO₂-Emissionen den Erdüberlastungstag beeinflussen. Datenquelle: Global Footprint Network (GFN), sektorale CO₂-Aufschlüsselung (1990–2024)."
    }
};

export default labels;